//! The Google Drive plugin for fizzy — a third-party plugin in the canonical shape: depend on
//! the fizzy SDK, call `fizzy.plugin.create` + `.install`. `zig build` produces
//! `drive.<dylib|dll|so>`; `zig build test` runs the Drive client and OAuth tests.
const std = @import("std");
const fizzy = @import("fizzy");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    ensureCredentials(b);

    const plugin = fizzy.plugin.create(b, .{ .target = target, .optimize = optimize });
    if (b.lazyDependency("icons", .{ .target = target, .optimize = optimize })) |dep| {
        plugin.module.addImport("icons", dep.module("icons"));
    }
    fizzy.plugin.install(b, plugin.lib, .{});

    // The plugin module carries the tests that need `core` (the Drive client over a scripted
    // transport) and the pure ones (OAuth pieces) alike.
    const test_step = b.step("test", "Run the Drive client and OAuth tests");
    const tests = b.addTest(.{ .name = "drive-tests", .root_module = plugin.module });
    test_step.dependOn(&b.addRunArtifact(tests).step);
}

/// `credentials.zon` is `@import`ed by `plugin.zig`, so it has to exist. A developer copies
/// `credentials.zon.example`; CI has none, so it is written from the environment — empty
/// strings when those are unset too, which builds a plugin that can only say "not configured".
fn ensureCredentials(b: *std.Build) void {
    const io = b.graph.io;
    if (b.build_root.handle.access(io, "credentials.zon", .{})) |_| return else |_| {}
    const id = b.graph.environ_map.get("FIZZY_DRIVE_CLIENT_ID") orelse "";
    const secret = b.graph.environ_map.get("FIZZY_DRIVE_CLIENT_SECRET") orelse "";
    const web_id = b.graph.environ_map.get("FIZZY_DRIVE_WEB_CLIENT_ID") orelse "";
    const key = b.graph.environ_map.get("FIZZY_DRIVE_API_KEY") orelse "";
    const project = b.graph.environ_map.get("FIZZY_DRIVE_PROJECT_NUMBER") orelse "";
    const text = b.fmt(
        \\// Generated by `zig build` from the environment (see credentials.zon.example). Not committed.
        \\.{{
        \\    .client_id = "{s}",
        \\    .client_secret = "{s}",
        \\    .web_client_id = "{s}",
        \\    .api_key = "{s}",
        \\    .project_number = "{s}",
        \\}}
        \\
    , .{ id, secret, web_id, key, project });
    b.build_root.handle.writeFile(io, .{ .sub_path = "credentials.zon", .data = text }) catch |err| {
        std.debug.panic("drive: could not write credentials.zon: {t}", .{err});
    };
    if (id.len == 0) std.debug.print("drive: no credentials.zon and FIZZY_DRIVE_CLIENT_ID unset — the plugin will refuse to sign in until one is provided\n", .{});
}
